version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_pass
    volumes:
      - /data/mysql
  appointment-app:
    image: appointmentapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 8076:8070
    volumes:
      - /data/compose-app